name: Auto Nexus CLI Manager

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # chạy mỗi 15 phút để check tiến trình

jobs:
  run-auto-manager:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODESPACE_NAME: scary-spooky-coffin-wqv595qjqx42wvg
      HOME: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Node 22.x như Codespaces của bạn

      - name: Install dependencies
        run: |
          npm install
          npm install node-fetch

      - name: Ensure log file exists
        run: |
          touch ~/auto.log

      - name: Run auto_manager in background
        run: |
          nohup node ~/auto_manager.js > ~/auto.log 2>&1 &
          echo "✅ auto_manager started in background"

      - name: Tail log for real-time feedback
        run: |
          tail -n 20 ~/auto.log
